# Writes Azure outputs from `azd provision` into backend/.env so the FastAPI
# app picks them up automatically on next start.

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$envFile = Join-Path $repoRoot 'backend\.env'

# Keys are intentionally NOT included: all data-plane auth is AAD via
# DefaultAzureCredential. Run `az login` locally before starting the app.
$keys = @(
  'AZURE_OPENAI_ENDPOINT',
  'AZURE_OPENAI_EMBEDDING_DEPLOYMENT',
  'AZURE_OPENAI_CHAT_DEPLOYMENT',
  'AZURE_AI_SEARCH_ENDPOINT',
  'AZURE_AI_SEARCH_INDEX',
  'FOUNDRY_PROJECT_ENDPOINT'
)

# Preserve any keys the user has set manually (e.g. FOUNDRY_AGENT_ID).
$existing = @{}
if (Test-Path $envFile) {
  Get-Content $envFile | ForEach-Object {
    if ($_ -match '^\s*([A-Z_][A-Z0-9_]*)\s*=(.*)$') {
      $existing[$matches[1]] = $matches[2]
    }
  }
}

# Pin the API version so it matches the deployed model.
$existing['AZURE_OPENAI_API_VERSION'] = '2024-10-21'

foreach ($k in $keys) {
  $val = [Environment]::GetEnvironmentVariable($k)
  if ($null -ne $val -and $val -ne '') {
    $existing[$k] = $val
  }
}

$lines = @("# Generated by azd postprovision hook on $(Get-Date -Format o)")
foreach ($k in ($existing.Keys | Sort-Object)) {
  $lines += "$k=$($existing[$k])"
}

New-Item -ItemType Directory -Force -Path (Split-Path $envFile) | Out-Null
$lines | Set-Content -Encoding utf8 $envFile

Write-Host "[postprovision] Wrote $($keys.Count) keys to $envFile"
if (-not $existing.ContainsKey('FOUNDRY_AGENT_ID') -or [string]::IsNullOrWhiteSpace($existing['FOUNDRY_AGENT_ID'])) {
  Write-Host ""
  Write-Host "Next step: create a Foundry agent on the new project, attach the" -ForegroundColor Yellow
  Write-Host "  '$($existing['AZURE_AI_SEARCH_INDEX'])' AI Search index as a knowledge source," -ForegroundColor Yellow
  Write-Host "  then set FOUNDRY_AGENT_ID=asst_xxx in $envFile." -ForegroundColor Yellow
}
