#!/usr/bin/env bash
# Writes Azure outputs from `azd provision` into backend/.env so the FastAPI
# app picks them up automatically on next start.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
env_file="${repo_root}/backend/.env"
mkdir -p "$(dirname "${env_file}")"

# Keys intentionally omitted: all data-plane auth is AAD via DefaultAzureCredential.
# Run `az login` locally before starting the app.
keys=(
  AZURE_OPENAI_ENDPOINT
  AZURE_OPENAI_EMBEDDING_DEPLOYMENT
  AZURE_OPENAI_CHAT_DEPLOYMENT
  AZURE_AI_SEARCH_ENDPOINT
  AZURE_AI_SEARCH_INDEX
  FOUNDRY_PROJECT_ENDPOINT
)

# Preserve user-managed keys (e.g. FOUNDRY_AGENT_ID).
declare -A existing
if [[ -f "${env_file}" ]]; then
  while IFS= read -r line; do
    if [[ "$line" =~ ^[[:space:]]*([A-Z_][A-Z0-9_]*)[[:space:]]*=(.*)$ ]]; then
      existing["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
    fi
  done < "${env_file}"
fi

existing[AZURE_OPENAI_API_VERSION]="2024-10-21"

for k in "${keys[@]}"; do
  v="${!k:-}"
  if [[ -n "${v}" ]]; then
    existing["$k"]="$v"
  fi
done

{
  echo "# Generated by azd postprovision hook on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  for k in $(printf '%s\n' "${!existing[@]}" | sort); do
    printf '%s=%s\n' "$k" "${existing[$k]}"
  done
} > "${env_file}"

echo "[postprovision] Wrote ${#keys[@]} keys to ${env_file}"

if [[ -z "${existing[FOUNDRY_AGENT_ID]:-}" ]]; then
  echo ""
  echo "Next step: create a Foundry agent on the new project, attach the"
  echo "  '${existing[AZURE_AI_SEARCH_INDEX]:-rag-cost-demo}' AI Search index as a knowledge source,"
  echo "  then set FOUNDRY_AGENT_ID=asst_xxx in ${env_file}."
fi
